removed workflow phases for now

diff --git a/.github/workflows/deploy-stage.yml b/.github/workflows/deploy-stage.yml
--- a/.github/workflows/deploy-stage.yml
+++ b/.github/workflows/deploy-stage.yml
@@ -50,12 +50,12 @@ jobs:
         with:
           os: ${{ matrix.os }}
           command: build
-      - name: Check required environment variables
-        run: |
-          if [ -z "${{ secrets.AIO_EVENTS_PROVIDERMETADATA_TO_PROVIDER_MAPPING_STAGE }}" ]; then
-            echo "Error: Required variable to deploy AIO_EVENTS_PROVIDERMETADATA_TO_PROVIDER_MAPPING_STAGE is not set."
-            exit 1
-          fi
+#      - name: Check required environment variables
+#        run: |
+#          if [ -z "${{ secrets.AIO_EVENTS_PROVIDERMETADATA_TO_PROVIDER_MAPPING_STAGE }}" ]; then
+#            echo "Error: Required variable to deploy AIO_EVENTS_PROVIDERMETADATA_TO_PROVIDER_MAPPING_STAGE is not set."
+#            exit 1
+#          fi
       - name: Deploy
         env:
           AIO_RUNTIME_NAMESPACE: ${{ secrets.AIO_RUNTIME_NAMESPACE_STAGE }}
@@ -68,7 +68,7 @@ jobs:
           AIO_PROJECT_WORKSPACE_DETAILS_SERVICES: ${{ secrets.AIO_PROJECT_WORKSPACE_DETAILS_SERVICES_STAGE }}
           SERVICE_API_KEY: ${{ secrets.SERVICE_API_KEY_STAGE }}
           AIO_PROJECT_ORG_IMS__ORG__ID: ${{ secrets.AIO_PROJECT_IMS_ORG_ID_STAGE }}
-          AIO_EVENTS_PROVIDERMETADATA_TO_PROVIDER_MAPPING: ${{ secrets.AIO_EVENTS_PROVIDERMETADATA_TO_PROVIDER_MAPPING_STAGE }}
+#          AIO_EVENTS_PROVIDERMETADATA_TO_PROVIDER_MAPPING: ${{ secrets.AIO_EVENTS_PROVIDERMETADATA_TO_PROVIDER_MAPPING_STAGE }}
         uses: adobe/aio-apps-action@3.3.0
         with:
           os: ${{ matrix.os }}
